/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   google-drive-list-view.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html, css} from 'lit-element';

declare namespace UiElements {

  /**
   * Google Drive files list view.
   *
   * It renders items using model returend by Google Drive API.
   *
   * Required properties of model items:
   * - capabilities.canDownload
   * - shared
   * - name
   * - createdTime
   * - size
   * - isAppAuthorized
   *
   * ## Styling
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--arc-font-body1-font-size` | ARC theme variable. Applied to the element. | `inherit`
   * `--arc-font-body1-font-weight` | ARC theme variable. Applied to the element. | `inherit`
   * `--arc-font-body1-line-height` | ARC theme variable. Applied to the element. | `inherit`
   * `--arc-font-headline-font-size` | ARC theme. Applied to the title | `initial`
   * `--arc-font-headline-font-weight` | ARC theme. Applied to the title | `initial`
   * `--arc-font-headline-letter-spacing` | ARC theme. Applied to the title | `initial`
   * `--arc-font-headline-line-height` | ARC theme. Applied to the title | `initial`
   * `--action-button-background-color` | ARC theme. Applied to action button | ``
   * `--action-button-background-image` | ARC theme. Applied to action button | ``
   * `--action-button-color` | ARC theme. Applied to action button | ``
   * `--action-button-transition`| ARC theme. Applied to action button | ``
   * `--google-drive-list-view-file-icon-color` | | `rgba(0, 0, 0, 0.54)`
   * `--google-drive-list-view-search-icon-color` | | `rgba(0, 0, 0, 0.54)`
   * `--google-drive-list-view-item-disabled-color` | | `rgba(0, 0, 0, 0.45)`
   * `--google-drive-list-view-selected-background-color` | | `#e0e0e0`
   */
  class GoogleDriveListView extends LitElement {
    readonly _search: any;

    /**
     * List of items to display. Query result from the Drive API
     */
    items: any[]|null|undefined;
    onrefreshlist: Function|null|undefined;
    onloadnext: Function|null|undefined;
    onfileopen: Function|null|undefined;
    onfileauthinfo: Function|null|undefined;
    onsearch: Function|null|undefined;

    /**
     * Current filter value
     */
    query: string|null|undefined;

    /**
     * Icon prefix from the svg icon set. This can be used to replace the set
     * without changing the icon.
     *
     * Defaults to `arc`.
     */
    iconPrefix: string|null|undefined;
    constructor();
    connectedCallback(): void;
    disconnectedCallback(): void;
    firstUpdated(): void;
    render(): any;
    _listItemTeamplate(item: any, iconPrefix: any): any;
    _listTemplate(items: any, iconPrefix: any): any;

    /**
     * Dispatches `load-next` event to inform parent element to load results.
     */
    nextPage(): void;

    /**
     * Dispatches `refresh-list` event to inform parent element to load results.
     */
    _refresh(): void;

    /**
     * Clears threshold triggers.
     */
    clearTriggers(): void;

    /**
     * Computes selection class name for the row items.
     */
    _computeItemClass(canDownload: any): any;

    /**
     * Sends the `drive-file-search` event to parent element with current query.
     */
    _searchAction(): void;

    /**
     * @returns A list item associated with current event.
     */
    _getTargetItem(e: Event|null): object|null|undefined;

    /**
     * Computes human readable size label from file size.
     *
     * @param bytes File size in bytes
     * @returns Human readable size
     */
    _computeSize(bytes: Number|null): String|null;

    /**
     * Computes value for search icon button's icon property.
     *
     * @param prefix Icons set prefix
     * @param iconName Search icon name.
     */
    _computeSearchIcon(prefix: String|null, iconName: String|null): String|null;

    /**
     * Computes an icon for an item.
     *
     * @param shared Item's shared flag
     * @param prefix Icons set prefix
     * @returns Icon full name.
     */
    _computeIcon(shared: Boolean|null, prefix: String|null): String|null;

    /**
     * Computes "title" attribute for the item's icon.
     *
     * @param shared Item's shared flag
     */
    _computeIconTitle(shared: Boolean|null): String|null;

    /**
     * Handler for "open" button click. Dispatches `file-auth-info` event.
     */
    _openItem(e: MouseEvent|null): void;

    /**
     * Handler for "info" button click. Dispatches `file-auth-info` event.
     */
    _downloadAppInfo(e: MouseEvent|null): void;

    /**
     * Handler for `input` event on search input field.
     */
    _queryInputHandler(e: Event|null): void;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "google-drive-list-view": UiElements.GoogleDriveListView;
  }
}
