/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   google-drive-browser.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html, css} from 'lit-element';

import {EventsTargetMixin} from '@advanced-rest-client/events-target-mixin/events-target-mixin.js';

declare namespace UiElements {

  /**
   * A file browser for Google Drive
   *
   * This component needs an access token to be provided in order to get data from user's Drive.
   *
   * ## Styling
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--arc-font-body1-font-size` | ARC theme variable. Applied to the element. | `inherit`
   * `--arc-font-body1-font-weight` | ARC theme variable. Applied to the element. | `inherit`
   * `--arc-font-body1-line-height` | ARC theme variable. Applied to the element. | `inherit`
   * `--action-button-background-color` | ARC theme. Applied to action button | ``
   * `--action-button-background-image` | ARC theme. Applied to action button | ``
   * `--action-button-color` | ARC theme. Applied to action button | ``
   * `--action-button-transition`| ARC theme. Applied to action button | ``
   */
  class GoogleDriveBrowser extends
    EventsTargetMixin(
    Object) {

    /**
     * OAuth 2 access token.
     */
    accessToken: string|null|undefined;
    ongoogleauthorize: any;
    ondrivefile: any;
    onoauth2tokeninvalid: any;

    /**
     * True if Google Drive operation pending
     */
    loading: boolean|null|undefined;

    /**
     * File search term entered by the user.
     */
    query: string|null|undefined;

    /**
     * List of files retreived from Drive API.
     */
    items: any[]|null|undefined;

    /**
     * OAuth2 scope for drive.
     */
    scope: string|null|undefined;

    /**
     * An error message from the API if any.
     */
    errorMessage: string|null|undefined;

    /**
     * If set it generates a query to Google Drive that contains query to file
     * properies.
     * E.g. (part of the query):
     * ```
     * and properties has { key='propertyKey' and value='propertyValue'}
     * ```
     *
     * Keys of this object will be put into the `key` part of query and
     * value of the key to the `value` property.
     *
     * For example:
     * ```
     * queryProperties = {
     *   'isExport': true
     * }
     * ```
     */
    queryProperties: object|null|undefined;

    /**
     * If true then it uses a negation for `queryProperties` (adding `not`)
     * before the query
     */
    queryPropertiesNegation: boolean|null|undefined;

    /**
     * A `pageSize` property value to be send to Drive endpoint.
     * Default: 50
     */
    querySize: Number|null;

    /**
     * Mime type of the file to search.
     */
    mimeType: string|null|undefined;

    /**
     * Currently opened view
     */
    selectedView: number|null|undefined;

    /**
     * Query parameters to be set with a file query call.
     */
    _queryParams: object|null|undefined;

    /**
     * API key to use as `key` query parameter.
     */
    apiKey: string|null|undefined;

    /**
     * Used when paginating over results, returned from Drive API.
     */
    _nextPageToken: string|null|undefined;

    /**
     * True when there's no more result for current query.
     */
    _hasMore: boolean|null|undefined;

    /**
     * When set it renders narrow view, mobile friendly.
     */
    narrow: boolean|null|undefined;
    _renderView(selectedView: any, narrow: any): any;
    render(): any;
    _attachListeners(node: any): void;
    _detachListeners(node: any): void;

    /**
     * Handler for the `google-signin-success` event. If the `scope`
     * property set on the `detail` object matches `scope` set on this element
     * then it sets the `accessToken` property from detail's `token` property.
     */
    _signedinHandler(e: CustomEvent|null): void;

    /**
     * Handler for the `google-signin-success` custom event.
     * Clears the `accessToken` property.
     */
    _signoutHandler(): void;

    /**
     * Checks if current `scope` matches passed `scope` value.
     *
     * @param scope Scope to check
     * @returns True if `scope` set on this element matches passed value.
     */
    _hasScope(scope: String|null): Boolean|null;

    /**
     * Chooses a view depending on athorization value.
     */
    _initView(): void;

    /**
     * Resets the view when token value change.
     */
    _accessTokenChanged(token: any): void;

    /**
     * Forces the view to display list view.
     */
    showList(): void;

    /**
     * Query for the files on Google Drive.
     */
    _queryFiles(): any;

    /**
     * Builds the query (`q`) parameter for Google Drive API.
     *
     * @returns A value for the `q` query parameter
     */
    _buildQuery(): String|null;

    /**
     * Updates the `queryParams` property for current UI state.
     */
    _setQueryParameters(): void;

    /**
     * Sets the authorization header on the Ajax request objects. It affects
     * query and download requests.
     *
     * @param at Access token value. If empty it clears the headers.
     */
    _setAuthHeader(at: String|null): void;
    refresh(): void;

    /**
     * Called when user accept search query.
     */
    _onSearch(e: CustomEvent|null): void;

    /**
     * Reset current query data.
     */
    _resetQuery(): void;

    /**
     * Handler for the Drive list response.
     *
     * @param response API call response
     */
    _onDriveListResponse(response: object|null): void;

    /**
     * Ajax call to Drive API error handler
     *
     * @param status Response status code
     * @param response API call response
     */
    _handleDriveApiError(status: Number|null, response: String|object|null): void;

    /**
     * The requesting app is not on the ACL for the file. The user never explicitly opened
     * the file with this Drive app.
     */
    _appNotAuthorizedToFile(): void;

    /**
     * If an item wasn't created by the application or never opened by it,
     * it is not possible to open an item with the API> User has to gi to
     * Drive UI and opend with ARC using Drive UI.
     * This opens the page that describe the issue.
     */
    _explainAppNotAuthorized(file: object|null): void;

    /**
     * Handler when user select a file from file picker.
     */
    _onOpenFile(e: CustomEvent|null): void;

    /**
     * Download and read a Google Drive item.
     *
     * @param id An item ID. This will show an error if the file wasn't created by this app
     * (e.g. old version of the app).
     */
    _downloadFile(id: String|null): any;

    /**
     * Ajax call success handler for file download.
     *
     * @param response API call response
     */
    _handleDownloadResponse(response: String|null): void;

    /**
     * Handles event sent by the list to display download info.
     */
    _appNotAuthorizedHandler(e: any): void;

    /**
     * Dispatches `oauth-2-token-invalid` event
     */
    _notifyInvalidToken(): void;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "google-drive-browser": UiElements.GoogleDriveBrowser;
  }
}
