/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   google-drive-authorize.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../paper-spinner/paper-spinner.d.ts" />
/// <reference path="../paper-button/paper-button.d.ts" />

declare namespace UiElements {

  /**
   * Authorize app screen for Google Drive file browser.
   *
   * ## Styling
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--google-drive-authorize` | Mixin applied to the element | `{}`
   * `--arc-font-headline` | Mixin applied to the header | `{}`
   * `--action-button` | Mixin applied to the main action button | `{}`
   */
  class GoogleDriveAuthorize extends Polymer.Element {

    /**
     * True to indicate that the app is being authorized.
     */
    authorizing: boolean|null|undefined;

    /**
     * Scope to call with authorize action.
     */
    scope: string|null|undefined;

    /**
     * Sends the `google-autorize` with scope for drive file picker.
     */
    authorize(): void;
  }
}

interface HTMLElementTagNameMap {
  "google-drive-authorize": UiElements.GoogleDriveAuthorize;
}
