/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   google-drive-authorize.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html, css} from 'lit-element';

declare namespace UiElements {

  /**
   * Authorize app screen for Google Drive file browser.
   *
   * ## Styling
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--arc-font-body1-font-size` | ARC theme variable. Applied to the element. | `inherit`
   * `--arc-font-body1-font-weight` | ARC theme variable. Applied to the element. | `inherit`
   * `--arc-font-body1-line-height` | ARC theme variable. Applied to the element. | `inherit`
   * `--arc-font-headline-font-size` | ARC theme. Applied to the title | `initial`
   * `--arc-font-headline-font-weight` | ARC theme. Applied to the title | `initial`
   * `--arc-font-headline-letter-spacing` | ARC theme. Applied to the title | `initial`
   * `--arc-font-headline-line-height` | ARC theme. Applied to the title | `initial`
   * `--action-button-background-color` | ARC theme. Applied to action button | ``
   * `--action-button-background-image` | ARC theme. Applied to action button | ``
   * `--action-button-color` | ARC theme. Applied to action button | ``
   * `--action-button-transition`| ARC theme. Applied to action button | ``
   */
  class GoogleDriveAuthorize extends LitElement {

    /**
     * True to indicate that the app is being authorized.
     */
    authorizing: boolean|null|undefined;

    /**
     * Scope to call with authorize action.
     */
    scope: string|null|undefined;
    constructor();
    connectedCallback(): void;
    disconnectedCallback(): void;
    render(): any;

    /**
     * Handler for Google auth events. Resets `authorizing` state when handled.
     */
    _authHandler(): void;

    /**
     * Dispatches `google-authorize` with scope for drive file picker.
     * Also sets `authorizing` to `true`.
     */
    authorize(): void;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "google-drive-authorize": UiElements.GoogleDriveAuthorize;
  }
}
