/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   google-drive-app-not-authorized.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html, css} from 'lit-element';

declare namespace UiElements {

  /**
   * An element that explains why the user can't open the file with
   * the application because the app is not on file's ACL list.
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--arc-font-body1-font-size` | ARC theme variable. Applied to the element. | `inherit`
   * `--arc-font-body1-font-weight` | ARC theme variable. Applied to the element. | `inherit`
   * `--arc-font-body1-line-height` | ARC theme variable. Applied to the element. | `inherit`
   * `--arc-font-headline-font-size` | ARC theme. Applied to the title | `initial`
   * `--arc-font-headline-font-weight` | ARC theme. Applied to the title | `initial`
   * `--arc-font-headline-letter-spacing` | ARC theme. Applied to the title | `initial`
   * `--arc-font-headline-line-height` | ARC theme. Applied to the title | `initial`
   * `--action-button-background-color` | ARC theme. Applied to action button | ``
   * `--action-button-background-image` | ARC theme. Applied to action button | ``
   * `--action-button-color` | ARC theme. Applied to action button | ``
   * `--action-button-transition`| ARC theme. Applied to action button | ``
   * `--secondary-action-button-color` | ARC theme. Applied to secondary button | `--primary-color`
   * `--google-drive-app-not-authorized-hint-color` | Hint color | `currentColor`
   * `--google-drive-app-not-authorized-link-block-background-color` | | `rgba(0, 0, 0, 0.2)`
   */
  class GoogleDriveAppNotAuthorized extends LitElement {

    /**
     * A drive file object
     */
    item: object|null|undefined;
    constructor();
    render(): any;
    back(): void;
    openDrive(): void;
    _dispatchOpenExtarnal(url: any): any;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "google-drive-app-not-authorized": UiElements.GoogleDriveAppNotAuthorized;
  }
}
